spring:
  application:
    name: client-update
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      discovery:
        enabled: true
        service-id: config-server1
  config:
    import: "optional:configserver:"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8085